### ISSUE TITLE
Change Project Ownership - User disappears until reload of project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#288]
1.New Proejct --> Change Owernship from ASUS Device to Surface Pro 
2.Change ownerhsip back from Surface Pro to ASUS Device. We do not see the ASUS User anymore under Info (we cannot selct him anyomre)
3.Rload project on ASUS Device
4.On Surface Pro we see the ASUS user again and can change project owernship

**Comment by corradocavalli** [comment]
Fixed in v102, please note that old administrator must reload the project in order to be visible on the new administrator list.

**Comment by gsantopaolo** [comment]
@mtg1986 can you please confirm this is fixed?

**Comment by mtg1986** [comment]
It is not fixed yet. Now I got a Panda: 

Repo Sequence: 
1.Create project on device one
2.Login to project on device two 
3.Change project owernship on device one to device two 
4.One device one owernship is succesfully transfered (I see the yellow start above the user Icon of device 2)
5.On device two project closes and CollaBoard asks to reload the project
6.When I try to reload the project on device two I get a Panda. 

Key: 9029
Code: km03l

**Comment by mtg1986** [comment]
Doing it the second and third time it worked. So I cannot reproduce anymore.

**Comment by corradocavalli** [comment]
Can you trying doing the same on different machines?

**Comment by mtg1986** [comment]
The behaviour is now like that: 

1.Create project on device 1
2.Login to project on device 2
3.Change project ownership from device 1 to 2 
4.On device 2 CollaBoard asks to reload the project 
5.I reload the project 
6.Go to info tile to switch ownership back to device 1 
7.User of device 1 is not displayed (he only appears when I reload to project on device 1).

**Comment by corradocavalli** [comment]
Are you using the same user for both machines or different, if same, can you repeat the same sequence using two different account please?
Thanks

**Comment by mtg1986** [comment]
I was using two different users. 
One was mine and the other Basils one.

**Comment by corradocavalli** [comment]
Ok, Thanks I'll investigate.

**Comment by corradocavalli** [comment]
@gsantopaolo The problem seems to be that after the switch of ownership from device1 to device2 when i call **GetUsersByProjectAsync** API still returns device1's owner instead of device2 so the list is empty because there are not eligible users on device2.

**Comment by corradocavalli** [comment]
Fixed in v109.
