### ISSUE TITLE
File of view jumping

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#629]
The filed of view is jumping on a Surface  while someone else is working on a HP Sepcture and putting a sticky note from ink to text edit mode. 

-->Needs to be deeply tested with the latest version. Was happening during the meeting with the Microsoft people.

**Comment by agorog** [comment]
This happened on Machineid c4d4b0c3-4796-6564-bcde-cdee582f80a2 using Version 2.0.41. Worked at same time in project with Verswion 2.0.42.0 and 2.0.45.0. @corradocavalli Has this been fixed with 2.0.42.0 ?

**Comment by corradocavalli** [comment]
Can you please elaborate more on what exactly happened? What 'file of view' jumping means?

On 31 Jul 2018, at 11:13, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


This happened on Machineid c4d4b0c3-4796-6564-bcde-cdee582f80a2 using Version 2.0.41. Worked at same time in project with Verswion 2.0.42.0 and 2.0.45.0. @corradocavalli<https://github.com/corradocavalli> Has this been fixed with 2.0.42.0 ?

**Comment by mtg1986** [comment]
I found a repo scenario for this bug.

Login to the same project with 2 users

1.Create Sticky Note on device one
2.Ink on the sticky note
3.On both devices the same sticky note is displayed.
4.Move in the canvas away from the first sticky note (on device two)
5.Create a new sticky note on device 2 (go to text edit mode on this sticky note)
-->Filed of view on device 1 is jumping (wihtout interacting with this device).

The following video demonstrates the scenario:
https://ibvinfo-my.sharepoint.com/:v:/g/personal/michael_gorog_ibv_ch/EaYmUSOHh8BIqYobznJh0qIByWHmFyUM_i_x4Ec1lZQUMQ

**Comment by corradocavalli** [comment]
Tricky one ever! Fixed in 2.0.52

**Comment by mtg1986** [comment]
I tested with 2.0.53 and it seems that I can still reproduce the bug with the same scenario.

**Comment by corradocavalli** [comment]
Sorry, it didn’t fit into build 53, try with next one.
